spring:
  application:
    name: book-service
  config:
    import: "optional:configserver:http://localhost:8889"
  cloud:
    config:
      enabled: true
      import-check:
        enabled: false

  datasource:
    url: jdbc:mysql://localhost:3306/mylibrarydb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  
  data:
    rest:
      base-path: /api

  # THÊM MỚI: Cấu hình Auth0 JWT validation
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-nkq0liomsorgp780.us.auth0.com/

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh
  endpoint:
    health:
      show-details: always